export { Login } from './login';
export { Cadastro } from './cadastro';
export { CadastroCurriculo } from './cadastro-curriculo';
export { Vagas } from './vagas';
export { Test } from './test';
export { Processos } from './processos';
export { ProcessosVaga } from './processos-vaga';
export { Perfil } from './perfil';
export { Curriculo } from './curriculo';